### PR TITLE
update exploding-trees

### PR DESCRIPTION
**Pull request by chayleaf**
- add compatibility for mods that add trees (like alien biomes)
- make robots also explode trees (but add a setting to disable it)
- make killing a tree always explode it (but add a setting to override the probability)
- add Russian and Japanese locale (the only two langs other than English that I know)

Side note, I think you should change the repository to not have the version number in the mod name. This will make the commit diffs way nicer.

### CODE REVIEW

**Comment by Zomis** [comment]
Thanks for the pull request.

I haven't bothered before about the version numbers in the mod names, even though I knew that they weren't needed. Because I built my Jenkinsfile to take care of the version updating, back in the day when the version number was required in the folder name.

Now I had a reason to update my Jenkinsfile though to also support mods without version number in folder name, thanks for that motivation :)

I have released a new version of the mod now, thanks!

**Comment by Zomis** [comment]
Btw... I can't believe someone is actually seriously playing with that mod 😂 I made it just for the fun of the quote.

**Comment by chayleaf** [comment]
I'm not actually playing with it, I just randomly tried it with SE installed lol

**Comment by Zomis** [comment]
@chayleaf That makes more sense. Thanks for the pull request anyway 😄

**Comment by riven8192** [comment]
in control.lua i see this line:
`local position = get_random_position(box, 0.8, 0.5)`

while the function only defines the 'box' parameters, so it ignores the 2nd and 3rd argument

**Pull request merged**
